name: Update indexer.json file

on:
  push:
    branches:
    - main

jobs:
  update-indexer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          ls -la
          sudo apt update
          sudo apt install python3 python3-venv python3-pip
          python3 -m venv indexer-venv
          pip install -r requirements.txt
          
      - name: update 
        run: |
          cd tools/indexer/
          source indexer-venv/bin/activate
          python3 indexer.py
