name: Update indexer.json file

on:
  push:
    branches:
    - main

jobs:
  update-indexer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: tools/indexer/requirements.txt
      - uses: stefanzweifel/git-auto-commit-action@v4

      
      - name: update 
        run: |
          cd tools/indexer/
          python3 indexer.py
