name: Update indexer.json file

on:
  push:
    branches:
    - main

jobs:
  update-indexer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      
      - name: update 
        run: |
          cd tools/indexer/
          pip install -r requirements.txt
          python3 -m venv indexer-venv
          source indexer-venv/bin/activate
          python3 indexer.py
